export const GET_PRODUCTLIST_REQUEST = "GET_PRODUCTLIST_REQUEST";
export const GET_PRODUCTLIST_SUCCESS = "GET_PRODUCTLIST_SUCCESS";
export const GET_PRODUCTLIST_FAIL = "GET_PRODUCTLIST_FAIL ";

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';