
export const PURCHASE_ORDER_CREATE_REQUEST = 'PURCHASE_ORDER_CREATE_REQUEST';
export const PURCHASE_ORDER_CREATE_SUCCESS = 'PURCHASE_ORDER_CREATE_SUCCESS';
export const PURCHASE_ORDER_CREATE_FAIL    = 'PURCHASE_ORDER_CREATE_FAIL';


export const GET_PURCHASE_ORDER_REQUEST = "GET_PURCHASE_ORDER_REQUEST";
export const GET_PURCHASE_ORDER_SUCCESS = "GET_PURCHASE_ORDER_SUCCESS";
export const GET_PURCHASE_ORDER_FAIL = "GET_PURCHASE_ORDER_FAIL";

export const GET_PURCHASE_ORDER_DETAIL_REQUEST = "GET_PURCHASE_ORDER_DETAIL_REQUEST";
export const GET_PURCHASE_ORDER_DETAIL_SUCCESS = "GET_PURCHASE_ORDER_DETAIL_SUCCESS";
export const GET_PURCHASE_ORDER_DETAIL_FAIL = "GET_PURCHASE_ORDER_DETAIL_FAIL";

export const PURCHASE_ORDER_CREATE_RESET = "PURCHASE_ORDER_CREATE_RESET"


export const TOTAL_PURCHASE_ORDER_REQUEST = "TOTAL_PURCHASE_ORDER_REQUEST";
export const TOTAL_PURCHASE_ORDER_SUCCESS = "TOTAL_PURCHASE_ORDER_SUCCESS";
export const TOTAL_PURCHASE_ORDER_FAIL = "TOTAL_PURCHASE_ORDER_FAIL";
