export const GET_WAREHOUSELIST_REQUEST = "GET_WAREHOUSELIST_REQUEST";
export const GET_WAREHOUSELIST_SUCCESS = "GET_WAREHOUSELIST_SUCCESS";
export const GET_WAREHOUSELIST_FAIL = "GET_WAREHOUSELIST_FAIL ";

export const GET_TOTALWAREHOUSE_REQUEST = "GET_WAREHOUSELIST_REQUEST";
export const GET_TOTALWAREHOUSE_SUCCESS = "GET_WAREHOUSELIST_SUCCESS";
export const GET_TOTALWAREHOUSE_FAIL = "GET_WAREHOUSELIST_FAIL ";


export const WAREHOUSE_CREATE_REQUEST = 'WAREHOUSE_CREATE_REQUEST';
export const WAREHOUSE_CREATE_SUCCESS = 'WAREHOUSE_CREATE_SUCCESS';
export const WAREHOUSE_CREATE_FAIL = 'WAREHOUSE_CREATE_FAIL';
export const WAREHOUSE_CREATE_RESET = 'WAREHOUSE_CREATE_RESET';

export const WAREHOUSE_UPDATE_REQUEST = 'WAREHOUSE_UPDATE_REQUEST';
export const WAREHOUSE_UPDATE_SUCCESS = 'WAREHOUSE_UPDATE_SUCCESS';
export const WAREHOUSE_UPDATE_FAIL = 'WAREHOUSE_UPDATE_FAIL';
export const WAREHOUSE_UPDATE_RESET = 'WAREHOUSE_UPDATE_RESET';


export const WAREHOUSE_DELETE_REQUEST = 'WAREHOUSE_DELETE_REQUEST';
export const WAREHOUSE_DELETE_SUCCESS = 'WAREHOUSE_DELETE_SUCCESS';
export const WAREHOUSE_DELETE_FAIL = 'WAREHOUSE_DELETE_FAIL';
export const WAREHOUSE_DELETE_RESET = 'WAREHOUSE_DELETE_RESET';